### ISSUE TITLE
Uncaught RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by urbantumbleweed** [TonyBrobston/jpegasus#118] opened 2019-07-16 21:38 UTC
I am running into an error when calling `jpegasus.compress`?

Here is a snippet of my code with comments
``` js
/**
 * @description Blobs are similar to File objects, this method converts blobs to file objects.  This was copied from a stackoverflow post.
 * https://stackoverflow.com/questions/27159179/how-to-convert-blob-to-file-in-javascript
 * @param {Blob} theBlob - blob object
 * @param {String} fileName - string to set as the `name` prop on the file object
 */
function blobToFile(theBlob, fileName) {
  // A Blob() is almost a File() - it's just missing the two properties below which we will add
  theBlob.lastModifiedDate = new Date(); // eslint-disable-line no-param-reassign
  theBlob.name = fileName; // eslint-disable-line no-param-reassign
  return theBlob;
}


Promise.all(
        map(pageCanvases, (pc, index) => {
          // return a promise here because we need to do nested async work.
          // when we have the compressed file blob, we resolve the promise.
          // if the compression fails, we resolve with a failover dataUrl generated by the canvas object
          return new Promise((innerResolve) => {
            try {
              // we get a blob from the canvas because our compression library needs a File object.  File inherits from blob.
              pc.toBlob((pageBlob) => {
              // changeDPI will change PNG to indicate it is 300dpi.
                changeDpiBlob(pageBlob, 300)
                  .then((upsampledBlob) => {
                    // since File objects needs a couple other properties to be considered File objects, we mutate the blob manually, see function above
                    const file = blobToFile(upsampledBlob, `page-${index}`);
                    // we now can pass the file object to the compression tool, and specify options.  We only specify quality though there are other options.
                    // https://github.com/TonyBrobston/jpegasus
                    const compressed = compress(file, {
                      quality: 0.80,
                    });
                    innerResolve(compressed);
                  });
              });
            } catch (error) {
              innerResolve(pc.toDataURL());
            }
          });
        })
      )
        .then(pageFiles =>...
```

The input to this code are dom elements that have been converted to canvas with `html2canvas`.

The output error doesn't appear to be fatal, but there also doesn't appear to be a way to address the issue.   Here is a screenshot of my error.  Let me know if there is anything else I can do to provide more context.

![DevTools_-_localhost_3001_transactions_listings_-Lh7LWF0zGEhvUl52Msm_marketing_requests](https://user-images.githubusercontent.com/1467882/61331653-1db94880-a7d7-11e9-961a-7bf52b355138.png)

**Comment by TonyBrobston** [comment] 2019-07-19 20:44
Hello @urbantumbleweed, thanks for reporting this issue.

I'm wondering two things:
1. What version of jpegasus are you running?
2. Do you have the image that you tried to compress and can I get access to it?

I had this particular issue a few weeks ago and put a fix in which mainly involved getting the orientation out of the exif data a different way. I think the issue is gone, so if you are running an older version upgrading may fix the issue. If that doesn't and I can get access to the image you're trying to compress I can look into it further.

Keep me in the look, I'll check this issue every few days.

**Comment by TonyBrobston** [comment] 2019-07-19 20:46
On second look, the code you've shown in the second screenshot is the updated way of getting orientation from the exif data, so you're on a pretty new version.

If you can provide the image I can definitely look into it.

**Comment by urbantumbleweed** [comment] 2019-07-19 21:11
Thank you for responding. I will need to extract the image from the
application on the next repro.  The images are dynamically generated from
the UI’s react component.

Thanks

**Comment by TonyBrobston** [comment] 2019-07-29 19:11
@urbantumbleweed I'm going to close this, if you get that image please reopen and I'll look into it! Thanks.

**Closed by TonyBrobston** 2019-07-29 19:11 UTC
